version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: binam
      POSTGRES_PASSWORD: Bhandari
      POSTGRES_DB: binam
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U binam"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  minio-server:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    command: server /data
    volumes:
      - ./minio-data:/data
      - ./minio-cors.json:/config/minio-cors.json

  userform:
    build:
      context: ./userform # Ensure this path points to the userform directory
      dockerfile: Dockerfile # Ensure the Dockerfile is named Dockerfile in the userform directory
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: binam
      DB_PASSWORD: Bhandari
      DB_NAME: binam
      MINIO_ENDPOINT: "minio-server:9000"
      MINIO_ACCESS_KEY: "B1IldoZs6RJWjsziHeIe"
      MINIO_SECRET_KEY: "BzX4nEffSluTotNmhcmAXRhS94jVSdT6m2mJdCaJ"
      MINIO_SSL: "false"
      EXTERNAL_MINIO_ENDPOINT: "http://<host-ip>:9000"
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend # Ensure this path points to the frontend directory
      dockerfile: Dockerfile # Ensure the Dockerfile is named Dockerfile in the frontend directory
    ports:
      - "3000:80"
